### ISSUE TITLE
OtoBeでプレゼンをする人として、アバターの手のサイズを変更出来るようにしたい、何故ならばどこを指しているか強調したいからだ

### ISSUE THREAD

**Issue by mmaccoss465** [OtoBe-Development/otobe-frontend#8]

**Comment by s-mikio** [comment]
- [ ] 直接、ハードコーディング（マジックナンバー）で手のサイズを設定して大きくできるようにする
- [ ] 変数に値を入れて手のサイズを大きくできるようにする
- [ ] スライダー経由でサイズを変更できるようにする
